- backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuAddRequest.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuResponse.java
- backend/src/main/java/com/backend/domain/menu/entity/Menu.java
- backend/src/main/java/com/backend/domain/menu/repository/MenuRepository.java
- backend/src/main/java/com/backend/domain/menu/service/MenuService.java
- backend/src/main/java/com/backend/global/response/ErrorCode.java
#42
사용자가 메뉴를 조회할 수 있는 메뉴 조회 API를 구현했습니다.
메뉴 조회 API 엔드포인트 구현
사용자 조회
GET /api/menu
관리자 조회
GET /api/admin/menu
응답 DTO(MenuResponse) 리스트 반환
DB 조회 로직
MenuRepository.findAll()을 통해 메뉴 목록 조회
응답 반환
성공 시 200 OK
메뉴 리스트를 MenuResponse DTO로 변환 후 반환
> feat: 메뉴 조회 기능 추가

- backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuUpdateRequest.java
- backend/src/main/java/com/backend/domain/menu/entity/Menu.java
- backend/src/main/java/com/backend/domain/menu/repository/MenuRepository.java
- backend/src/main/java/com/backend/domain/menu/service/MenuService.java
#70 
관리자가 기존 메뉴의 정보를 수정할 수 있는 메뉴 수정 API (PUT /api/admin/menu/{menuId}) 를 구현했습니다.
메뉴 이름, 가격, 품절 여부, 설명, 이미지 URL을 수정할 수 있습니다. 
수정을 시도할 때 기존의 메뉴 정보를 불러와야하기 때문에 메뉴 상세 조회 API(GET /api/admin/menu/{menuId})도 추가하였습니다.
- MenuUpdateRequest DTO 생성
- Menu 엔티티에 updateMenu() 메서드 추가
- MenuService.updateMenu() 구현
- 메뉴 ID로 기존 엔티티 조회
- 자기 자신 제외한 이름 중복 검사 (existsByNameAndMenuIdNot)
- MenuController.updateMenu() 구현
- PUT /api/admin/menu/{menuId} 엔드포인트 추가
- 수정된 메뉴 정보를 MenuResponse로 반환
- 단건 조회 API (GET /api/admin/menu/{menuId}) 추가 → 프론트에서 수정 시 기본값 채워주기 용도
[2번 메뉴 품절로 수정처리]
[2번 메뉴가 품절되어 사용자 조회에서는 출력되지않음]
당장 반영하려는 사항은 아닌데 만약에 나중에 다시 이런 서비스를 만들게 되면 단순히 품절 여부로 처리하는게 아니라 ENUM 형식으로 ON_SALE, SOLD_OUT, COMING_SOON 이런식으로 단순히 품절 여부만이 아닌 각각의 상태값을 가지는게 낫지 않을까 좀 고민이 됩니다.
> feat: 메뉴 수정 기능 추가

- backend/src/main/java/com/backend/domain/order/controller/OrderController.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderCreateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderDetailsCreateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryDetailResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryResponse.java
- backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
- backend/src/main/java/com/backend/domain/order/service/OrderService.java
#79 #86
일단 와이어프레임 보면서 대략적으로 dto 작성해서 db에 들어가는 것 까지는 확인했습니다.
예외 처리까지 진행 완료 했습니다.
- 사용자가 존재하는지
- 주문 목록이 있는지 확인 하도록 예외처리했습니다!
- 컨트롤러 구현
- 로직 구현(주소가 필요할 것 같기는 한데 일단 주석 처리 해놨습니다.)
- dto 작성(OrderSummaryResponse에서 주소 일단 주석 처리 해놨습니다.)
- 예외 처리 진행 중
------------------------------------------------------------------
OrderCreateRequest에서 이메일을 받아오도록 했었는데
쿠키를 사용함에 따라
```
public record OrderCreateRequest(
@Min(0) int amount,
@NotEmpty List<OrderDetailsCreateRequest> items
) {
}
```
로 변경되었습니다.
```
@GetMapping
@Operation(summary = "사용자 주문 목록 조회")
public ResponseEntity<ApiResponse<List<OrderSummaryResponse>>> getOrders() {
//쿠키에서 인증된 유저 가져오기
Users actor = rq.getUser();
//주문 조회 로직
List<OrderSummaryResponse> summaries = orderService.getOrdersByUserId(actor.getUserId());
return …
```
> feature: 사용자 주문 조회 기능 추가

- backend/src/main/java/com/backend/domain/order/controller/AdminOrderController.java
- backend/src/main/java/com/backend/domain/order/controller/OrderController.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderCreateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderDetailsCreateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/response/AdminOrderSummaryResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryDetailResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryResponse.java
- backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
- backend/src/main/java/com/backend/domain/order/service/AdminOrderService.java
- backend/src/main/java/com/backend/domain/order/service/OrderService.java
#90 
관리자가 주문 목록 조회 할 수 있게 구현했습니다.
사용자 주문 목록 조회와 크게 다를 건 없지만 AdminOrderSummaryResponse로 관리자는 더 많은 정보를 볼 수 있게 작성했습니다.
```
//쿠키에서 인증된 유저 가져오기
Users actor = rq.getUser();
// 관리자 권한 체크 (예: level == 1 이상만)
if (actor.getLevel() < 1) {
throw new BusinessException(ErrorCode.FORBIDDEN_ADMIN);
}
```
임의로 관리자 권한 체크 로직을 만들어 놨는데 추후에 수정하겠습니다.
잘 됐는지 확인 부탁드립니다!
> feature: 관리자 주문 목록 조회 기능 추가

- backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuUpdateRequest.java
- backend/src/main/java/com/backend/domain/menu/entity/Menu.java
- backend/src/main/java/com/backend/domain/menu/repository/MenuRepository.java
- backend/src/main/java/com/backend/domain/menu/service/MenuService.java
#85 
관리자가 기존에 등록된 메뉴를 삭제할 수 있는 메뉴 삭제 API (DELETE /api/admin/menu/{menuId})를 구현했습니다.
관리자는 더 이상 판매하지 않는 메뉴를 DB에서 제거할 수 있습니다.
- 메뉴 ID로 엔티티 조회 (findById)
- 존재하지 않을 경우 BusinessException(ErrorCode.NOT_FOUND_PRODUCT) 발생
- 메뉴 존재 시 menuRepository.delete() 호출
- MenuController.deleteMenu() 구현
- DELETE /api/admin/menu/{menuId} 엔드포인트 추가
- 삭제 성공 시 ApiResponse.success(null) 반환
[3번 메뉴 삭제]
> feature: 메뉴 삭제 기능 추가

- backend/src/main/java/com/backend/domain/payment/dto/request/PaymentCreateRequest.java
- backend/src/main/java/com/backend/domain/payment/dto/response/PaymentCreateResponse.java
- backend/src/main/java/com/backend/domain/payment/dto/response/PaymentInquiryResponse.java
- backend/src/main/java/com/backend/domain/payment/entity/Payment.java
- backend/src/main/java/com/backend/domain/payment/entity/PaymentMethod.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
예지 님이 말씀하신 방식으로 Service에서 Payment builder 이용하는 부분을 DTO에 메소드 만들어 분리 작성했고, 
GlobalExceptionHandler 이용한 에러 처리 방식도 진행 중에 있습니다!
PaymentCreateRequest.java
```   public Payment createPayment(Orders orders) {
return Payment.builder()
.paymentAmount(paymentAmount)
.paymentMethod(paymentMethod)
.orders(orders)
.build();
}
```
PaymentService.java
```
Payment payment = request.createPayment(orders);
```
--
에러 처리 결과 예시1. 이미 결제된 주문을 다시 결제하고자 할 때
외에 주문 금액과 결제 금액이 동일하지 않을 때, 결제 금액이 0보다 작거나 음수일 때, 결제 방식이 허락되지 않은 방식일 때 예외 처리 해 두었습니다!
추후 최종 수정 때 추가해 작성하도록 하겠습니다.
> feat: PaymentMethod 관련 enum 추가, PaymentDTO 개선

- backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuAddRequest.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuUpdateRequest.java
- backend/src/main/java/com/backend/domain/menu/entity/Menu.java
- backend/src/main/java/com/backend/domain/menu/service/MenuService.java
#100
예지님이 말씀하신 서비스 부분에서 new 보다는 DTO부분에서 rebuild로 처리 하는게 나을 것 같아 개선했습니다.
관리자 권한 검증 로직을 컨트롤러에 적용했습니다.
- MenuAddRequest DTO에 toEntity() 메서드 추가 (Builder 활용)
- MenuService에서 엔티티 변환 로직 제거
- 관리자 권한 검증 메서드(validateAdmin) 추가
- 메뉴 생성/수정/삭제 API 컨트롤러에 관리자 권한 검증 적용
- 현재 Rq.getUser()에서 throws Exception이 선언되어 있어 컨트롤러 메서드에도 throws Exception을 붙였습니다. 
- 관리자 권한 레벨을 하드코딩(1)으로 비교하고 있는데, 추후 enum 전역변수로 선언해두는게 나을 것 같습니다.
> refactor(menu): 엔티티 개선 및 관리자 권한 검증 로직 개선

- backend/src/main/java/com/backend/domain/payment/controller/PaymentController.java
- backend/src/main/java/com/backend/domain/payment/dto/response/PaymentCancelResponse.java
- backend/src/main/java/com/backend/domain/payment/entity/Payment.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
- backend/src/main/java/com/backend/global/response/ErrorCode.java
Closed #110 
결제 단건 취소 API 구현했습니다.
5c15309
1. PaymentController -> PUT 요청의 /api/payments/{paymentId}/cancel 생성
```
@PutMapping("/{paymentId}/cancel")
public ResponseEntity<ApiResponse<PaymentCancelResponse>> cancelPayment(
@Valid @PathVariable Long paymentId
)
... 중략
```
2. PaymentCancelResponse -> 결제 단건 취소 응답 DTO
3. Payment -> 결제 단건 취소 관련 비즈니스 로직 작성
```
public void cancel() {
if(this.paymentStatus == PaymentStatus.CANCELLED) {
throw new BusinessException(ErrorCode.PAYMENT_ALREADY_CANCELLED);
}
this.paymentStatus = PaymentStatus.CANCELLED;
}
```
4. PaymentService -> 결제 단건 취소 관련 서비스 로직 작성
```
@Transactional
public PaymentCancelResponse cancelPayment(@Valid Long paymentId) {
... 중략
```
> feature: 결제 단건 취소 API

- backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuAddRequest.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuSoldOutRequest.java
- backend/src/main/java/com/backend/domain/menu/dto/MenuUpdateRequest.java
- backend/src/main/java/com/backend/domain/menu/entity/Menu.java
- backend/src/main/java/com/backend/domain/menu/service/MenuService.java
#103 
관리자가 특정 메뉴를 품절 처리할 수 있는 API를 구현했습니다.  
메뉴의 상태값을 isSoldOut으로 업데이트합니다.  
- PATCH /api/admin/menu/{menuId}/isSoldOut 엔드포인트 추가 
- 관리자 권한 검증 후 isSoldOut 상태값 업데이트 
- 메뉴 존재 여부 확인 후 처리
- 성공 시 변경된 메뉴 정보 반환
> feature(menu): 메뉴 품절 처리 기능 구현

- backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
- backend/src/main/java/com/backend/domain/payment/controller/PaymentController.java
- backend/src/main/java/com/backend/domain/payment/entity/Payment.java
- backend/src/main/java/com/backend/domain/payment/entity/PaymentStatus.java
- backend/src/main/java/com/backend/domain/payment/repository/PaymentRepository.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
- backend/src/main/java/com/backend/global/response/ErrorCode.java
Closed #118 
Closed #124 
결제 단건 삭제 API 작성
Payment 전반에 Rq 도입, 사용자 검증
e717368: 결제 단건 취소로 작성되어야 하는데 결제 단건 삭제로 작성되어 있던 주석을 수정했습니다
9b5510f: 결제 단건 삭제 API
1. 사용자가 결제 취소된 건에 대해 데이터 삭제 요청을 할 경우 삭제 진행
2. 단, 결제가 취소된 건에 대해서만 삭제 요청 가능. 외에는 오류 처리
3. PaymentController, PaymentService, Payment, ErrorCode 수정했습니다!
4. **PaymentStatus enum 파일에서 CANCELLD -> CANCELD 오타 수정했습니다. -> Payment 테이블 삭제 후 다시 생성 부탁드립니다...**
**7529c1a: Payment 전반에 Rq 도입, 사용자 검증**
따로 브랜치를 파서 작업하려다가 delete도 추가적으로 작업되어야 하기에 한 브랜치에 작업했습니다...
1. OrderRepository 코드 payment -> order -> user 검증 코드 추가
```java
// 특정 주문이 요청한 사용자의 소유인지 검증하며 주문 조회
// (결제 권한 검증용: Payment → Orders → User 경로로 소유자 확인)
Optional<Orders> findByOrderIdAndUser_UserId(Long orderId, Long userId);
```
2. PaymentController, PaymentService 전반에 rq 도입 및 검증 코드 추가
> feat: 결제 단건 삭제 API, Payment 도메인 전반 사용자 검증 도입

- backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
#123 
MenuController 내 관리자 권한 검증 로직을 BaseInitData 설정과 일치하도록 수정했습니다.
기존에는 관리자 레벨 = 1 기준으로 검증했으나, 초기 데이터에서는 관리자 레벨 = 0 / 사용자 레벨 = 1로 설정되어 있어 권한이 반대로 동작했습니다.
검증 조건을 actor.level() != 0 으로 변경하여 정상적으로 관리자 계정만 메뉴 생성/수정이 가능하도록 수정했습니다.
> fix: 메뉴 컨트롤러 관리자 권한 레벨 수정

- backend/src/main/java/com/backend/domain/order/controller/AdminOrderController.java
- backend/src/main/java/com/backend/domain/order/controller/OrderController.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderCreateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/response/AdminOrderSummaryResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderDetailsCreateResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryDetailResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryResponse.java
- backend/src/main/java/com/backend/domain/order/entity/OrderDetails.java
- backend/src/main/java/com/backend/domain/order/entity/Orders.java
- backend/src/main/java/com/backend/domain/order/service/AdminOrderService.java
- backend/src/main/java/com/backend/domain/order/service/OrderService.java
#126 
관리자 인증 로직 구현했고 
주문 상태 업데이트 API는 관리자만 사용할 것 같아 `AdminOrderController`로 옮겼습니다. 
`http://localhost:8080/api/admin/orders/1/status` 로 바꿨습니다.
주문 생성했을 때 
```
{
"amount": 50000,
"addressId": 1,
"items": [
{ "productId": 1, "menuName": "콜롬비아", "quantity": 2, "orderPrice": 50000 }
]
}
```
로 addressId로 주소 받아올 수 있게 변경했습니다.
인증된 사용자가 개별 주문을 조회 할 수 있는 기능 구현했습니다.
> feat:관리자 기능 구현 및 주문 조회 시 주소 보이게 구현

- backend/build.gradle
- backend/src/main/java/com/backend/BackendApplication.java
- backend/src/main/java/com/backend/domain/payment/entity/Payment.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentFactory.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentProcessor.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentRetry.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
- backend/src/main/java/com/backend/domain/payment/service/RandomPaymentProcessor.java
- backend/src/test/java/com/backend/domain/payment/service/PaymentServiceTest.java
#130 
결제 요청 시 성공/승인에 따른 상태 변화 코드 수정했습니다.
12c3cdf:  Payment에 결제 실패 비즈니스 로직 추가
745c5dc: 기존의 결제 요청 코드에서 성공, 실패 시 각각 다른 상태 값을 가질 수 있도록 수정했습니다.
1. 결제 요청은 총 2회 시도하며, 모든 시도 실패 시 결제 상태가 FAILED인 결제 데이터를 생성하도록 리팩토링했습니다.
-> 주문의 경우, 실패한 결제 정보가 연결되지만 상태는 CREATED를 유지합니다.
-> **[종수 님 확인 사항] 결제 성공 시에만 주문 상태가 PAID로 변경되게 구현했습니다.**
2fea0d4: createPayment 메서드가 여러 개의 책임을 갖고 있는 것 같아 로직 분리했습니다.
d845ec2: 기존에 for문으로 작성했던 재시도 로직을 **Spring retryable 라이브러리** 이용해 수정했습니다.
32f6468: 결제 생성 시 성공, 실패를 기준으로 테스트 코드 작성했습니다.
현재 구현된 결제는 70%의 성공 확률을 갖도록 설계하였으며, 
해당 부분은 mock 결제에서 결제 실패 시 로직을 설계하기 위해 임의로 작성된 코드이기 때문에 PG사와 같은 실 결제 서비스 도입 시 변경될 예정입니다.
> refactor: 결제 요청 시 성공/승인에 따른 상태 변화 코드 수정

- backend/src/main/java/com/backend/global/WebConfig/WebConfig.java
- frontend/src/app/admin/page.tsx
- frontend/src/app/menu/page.tsx
#136 
- 사용자가 품절되지 않은 메뉴만 확인할 수 있는 사용자 전용 메뉴 페이지를 구현했습니다. (/menu)
- 관리자가 메뉴를 효율적으로 관리할 수 있도록 관리자 전용 대시보드를 구현했습니다. (/admin)
- 메뉴의 생성, 수정, 삭제, 품절 상태 토글 기능을 제공하여 메뉴 관리가 가능하도록 했습니다.
- 사용자 메뉴 페이지 기본 레이아웃 및 UI 구성
- 품절 되지 않은 메뉴 전체 조회 (GET /api/menu)
- 관리자 대시보드 기본 레이아웃 및 UI 구성
- 메뉴 전체 조회 API 연동 (GET /api/admin/menus)
- 새 메뉴 생성 모달 구현 및 API 연동 (POST /api/admin/menus)
- 기존 메뉴 수정 모달 구현 및 API 연동 (PUT /api/admin/menus/{menuId})
- 메뉴 품절 여부 토글 기능 구현 (PATCH /api/admin/menus/{menuId}/isSoldOut)
- 메뉴 삭제 기능 구현 (DELETE /api/admin/menus/{menuId})
> feature: 메뉴/관리자 대시보드 페이지 구현

- backend/src/main/java/com/backend/domain/order/service/OrderService.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
Closed #130 
주문 취소, 주문 삭제가 마무리되기 전 결제 삭제, 결제 취소를 선제적으로 진행하도록 수정했습니다.
d645661: 주문 취소, 주문 삭제가 진행되기 전에 결제 취소, 결제 삭제가 먼저 진행
기존에 작성했던 서비스 로직은 건들지 않고, 새로운 메서드로 작성했기 때문에 controller를 통해 개별 요청은 여전히 가능합니다.
종수 님 확인해 주세요!
> refactor: 주문-결제 취소, 삭제 연동

- backend/src/main/java/com/backend/domain/order/dto/response/AdminOrderSummaryResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderSummaryDetailResponse.java
- backend/src/main/java/com/backend/domain/order/service/AdminOrderService.java
- backend/src/main/java/com/backend/domain/order/service/OrderService.java
- frontend/src/app/orders/admin/page.tsx
- frontend/src/app/orders/page.tsx
- frontend/src/app/payment/page.tsx
#143
useEffect에서 3가지 API 호출:
GET /api/users/address/list → 사용자의 배송지 목록 불러오기
첫 번째 주소를 기본값으로 selectedId에 세팅.
GET /api/users/my → 현재 로그인된 유저 정보(email, phoneNumber).
GET /api/carts → 장바구니 아이템 목록 + 총 금액(grandTotal).
👉 이 데이터들이 각각 state에 들어감: addresses, user, cart.
배송 정보 영역
드롭다운으로 배송지 선택 가능 (selectedId).
선택된 유저 이메일, 연락처 표시 (수정 불가).
결제 요약 영역
장바구니 아이템 리스트 (cart.cartItems) 출력.
상품 이미지, 이름, 수량, 합계(orderAmount).
최종 합계 금액(grandTotal) 표시.
“결제하기” 버튼 노출.
버튼 클릭 시 실행되는 흐름:
selectedId === null → “배송지를 선택해주세요.”
장바구니가 비었으면 → “장바구니가 비어있습니다.”
서버에서 주문 생성 → orderId 반환.
결제 생성 (POST /api/payments/create)
서버에서 mock 결제 처리 → 주문 상태가 PAID로 변경됨.
주문 내역 페이지로 이동
router.push("/orders") 호출.
이후 주문 목록 화면에서 확인 가능.
장바구니 → 주문 생성 → 결제 처리 → 주문 내역 이동
프론트는 주문/결제 요청만 하고,
주문 상태 변경(CREATED → PAID)은 백엔드가 결제 API에서 처리.
> feature : 주문/결제 페이지 구성

- backend/src/main/java/com/backend/global/init/BaseInitData.java
#157 
테스트 환경에서 사용할 수 있도록 기본 메뉴 데이터를 초기화하는 기능을 추가했습니다.  
애플리케이션 실행 시 BaseInitData를 통해 기본 계정(관리자/사용자)과 함께 메뉴 데이터 5개가 자동 삽입되도록 구현했습니다.
1. `BaseInitData`에 기본 메뉴 생성 로직 추가  
2. DB에 메뉴 데이터가 없는 경우 초기 데이터 삽입 처리  
4. 예지님이 제공해주신 메뉴 데이터를 토대로 에티오피아 예가체프 G1, 콜롬비아 수프리모, 케냐 AA, 브라질 산토스, 품절 메뉴 총 5개 등록  
5. 각 메뉴에 이름, 가격, 설명, 이미지 URL 포함
> chore: 테스트를 위한 기본 메뉴 추가

- backend/src/main/java/com/backend/domain/menu/service/MenuService.java
- frontend/src/app/menu/page.tsx
- frontend/src/components/header.tsx
- frontend/src/context/AuthContext.tsx
#162 
사용자 메뉴 조회 화면에서 품절 상태의 메뉴도 회색 처리 및 "품절" 배지와 함께 표시되도록 개선했습니다.
또한 메뉴를 장바구니에 담을 경우, 하단에 장바구니 이동 UI가 나타나도록 수정하여 사용자 경험을 향상시켰습니다.
헤더에 관리자 로그인 시 관리자 대시보드 메뉴 추가하였습니다.
- 메뉴 조회 시 품절 메뉴도 함께 표시되도록 수정
- 품절 메뉴의 이미지에 회색 처리 적용 및 "품절" 배지 노출
- 품절 메뉴의 장바구니 버튼 비활성화 처리
- 장바구니 담기 성공 시 화면 하단에 알림 UI(토스트) 표시
- 알림 UI에서 "장바구니로 이동" 버튼 제공 → 클릭 시 /cart 페이지로 이동
- 관리자 로그인시 level 확인하여 관리자 대시보드 표시
[품절 메뉴가 포함된 메뉴 조회]
[장바구니 담기 버튼 클릭 시 하단에 장바구니 UI 표시]
> feature: 메뉴 조회 개선(품절 포함), 장바구니 이동 UI추가

- frontend/src/app/admin/page.tsx
- frontend/src/app/menu/page.tsx
- frontend/src/components/header.tsx
#166 
장바구니 담기 시 최신 데이터가 즉시 반영되도록 리패치 로직을 추가했습니다.
또한 관리자 계정으로 로그인했을 때 전체 유저의 주문 목록을 조회할 수 있도록 API와 프론트엔드 권한 검증 로직을 개선했습니다.
- 장바구니 담기 성공 시 refetch() 호출을 통해 헤더 및 UI에 즉시 반영되도록 수정
- 관리자 계정 로그인 시 전체 주문 목록을 조회할 수 있도록 API 수정
- 일반 사용자 로그인 시 본인 주문 목록만 조회되도록 권한 검증 로직 추가
- 관리자 전용 페이지(AdminDashboard) 접근 시 권한 검증 로직 추가 (관리자가 아닐 경우 접근 제한)
- 프론트엔드에서 관리자 여부에 따라 주문 내역 화면을 분기 처리
- 장바구니 담기 버튼 클릭 시 헤더에 있는 장바구니 카운트가 즉시 표출되도록 리패치 수정
- 사용자와 관리자 로그인 시 각각 다른 주문내역 목록이 보이도록 수정
- 로그인 리패치랑 아직 연계가 안돼서 혹시 병합되고 어색하거나 오류가 보이시면 말씀해주세요!
> feature: 장바구니 담기 시 리패치, 관리자 권한 검증 후 주문목록 표출, 관리자 대시 보드 접근

- frontend/src/app/orders/admin/page.tsx
- frontend/src/app/orders/page.tsx
- frontend/src/app/payment/page.tsx
50000원 아래이면 배송비가 3000원으로 보이고
50000원 이상이면 배송비가 무료로 보이도록 수정했습니다.
주문 내역에서 결제 실패한 건에 대해서 결제 조회 막고
주문 내역에서 결제 실패한 건은 결제 실패 빨간색으로 표시되게 수정했습니다
> fix:결제 페이지 배송비 뜨게 수정 + 결제 내역 관련 수정

- backend/src/main/java/com/backend/domain/payment/service/RandomPaymentProcessor.java
- frontend/src/app/payment/fail/page.tsx
- frontend/src/app/payment/page.tsx
- frontend/src/app/payment/success/page.tsx
#180 
주문 완료 페이지 - 장바구니 아이콘 refetch, 배송 주소, 결제 금액 UI, 로그인 접근 관련 수정
6290e2a: 결제 성공률 50%로 하향 조정했습니다
5abb714: 주문 생성 시 장바구니 아이콘이 비워지도록 refetch 설정했습니다
207b680: 주문 완료 페이지에 배송 주소가 상세 주소만 뜨던 점과 배송비 확인 가능하게끔 UI 수정했습니다
00e3cd0: 로그인하지 않으면 payment 관련 도메인에 접근 불가하도록 수정했습니다
5abb714: 주문 생성 시 장바구니 아이콘이 비워지도록 refetch 설정했습니다
207b680: 주문 완료 페이지에 배송 주소가 상세 주소만 뜨던 점과 배송비 확인 가능하게끔 UI 수정했습니다
> refactor(payment): 장바구니 아이콘 refetch, 배송 주소, 결제 금액 UI, 로그인 접근

- frontend/src/app/orders/admin/page.tsx
- frontend/src/app/orders/page.tsx
- frontend/src/components/admin-order-card.tsx
- frontend/src/components/order-item.tsx
관리자 주문 조회 페이지 컴포넌트 분리했습니다.
색상도 약간 수정해서 
결제 실패: 빨간색,
결제 완료: 파란색,
배송 완료: 회색,
주문 취소: 빨간색 으로 표시되게 바꿨습니다!
> feat:[FE] 관리자 주문 조회 페이지 리펙토링 및 약간의 색상 변경
