- backend/src/main/java/com/backend/domain/user/user/controller/UserController.java
- backend/src/main/java/com/backend/domain/user/user/dto/UserDto.java
- backend/src/main/java/com/backend/domain/user/user/entity/User.java
- backend/src/main/java/com/backend/domain/user/user/service/UserService.java
#14 이슈와 관련된 작업입니다. 
ERD 를 기반으로 데이터를 저장하고 불러올 User 클래스를 엔티티로서 작성
_필드명이 괜찮은지 확인해주시고, 일단은 ERD 기준으로 필드명을 작성했습니다._  
대신 DTO는 자바의 클래스 명명 규칙에 맞췄습니다. 
-> 카멜 케이스로 통일했습니다.
DTO에 생성자 추가하였습니다.
커밋에 어제 작업하던거 일부가 섞였는데 빼려면 좀 꼬일것 같아서 일단 같이 넣었습니다. 앞으로는 주의하겠습니다.
확인해주세요
> feat : User 엔티티 추가

- backend/src/main/java/com/backend/domain/order/entity/Order.java
Order 엔티티의 테이블명 orders 수정했습니다.
> feat: Order 테이블 명 수정

- backend/src/main/java/com/backend/domain/cart/entity/Cart.java
- backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
> feat: 장바구니 엔티티 생성

- backend/src/main/java/com/backend/domain/menu/entity/Menu.java
ERD 변경에 따라 엔티티와 DB 매핑을 수정하는 과정에서 불필요한 칼럼 매핑이 포함되어 실행 오류가 발생
엔티티에서 실제 사용하지 않는 칼럼 매핑 제거
ERD 수정 사항에 맞춰 필드명 및 어노테이션 정리
> feat: menu 엔티티 ERD 칼럼 매핑 삭제

- backend/src/main/java/com/backend/domain/cart/controller/CartController.java
- backend/src/main/java/com/backend/domain/cart/controller/dto/request/CartAddRequest.java
- backend/src/main/java/com/backend/domain/cart/controller/dto/response/CartResponse.java
- backend/src/main/java/com/backend/domain/cart/repository/CartRepository.java
- backend/src/main/java/com/backend/domain/cart/service/CartService.java
- backend/src/main/java/com/backend/global/exception/BusinessException.java
- backend/src/main/java/com/backend/global/exception/GlobalExceptionHandler.java
Closed #34 
장바구니에 메뉴 추가 후 메뉴와 사용자에 대한 정보 반환
- 정적 팩토리 메소드 추가
- 예외 처리를 위한 로직 추가
- 장바구니 메뉴 추가 기능 구현
- 테스트 데이터 넣은 후 테스트
> feature: 장바구니 메뉴 추가 기능 구현

- backend/src/main/java/com/backend/domain/user/address/dto/AddressDto.java
- backend/src/main/java/com/backend/domain/user/address/entity/Address.java
- backend/src/main/java/com/backend/domain/user/address/repository/AddressRepository.java
- backend/src/main/java/com/backend/domain/user/address/service/AddressService.java
- 주소를 저장할 Address 엔티티 클래스를 추가하였습니다.
주소 저장할 때 사용할 주소 엔티티를 만들었습니다.
주소 ID : addressId
회원 FK : userId
상세주소 : addressDetail
주소 : address
우편번호 : postNumber
``` java
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long addressId;
@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "user_id", nullable = false)
private Users user;
private String address;
private String addressDetail;
private String postNumber;
```
관계 설정은 매번 헷갈리네요 이게 맞는지 확인 부탁 드립니다...
> feature(address) : 주소 저장할 address 엔티티 클래스 추가

- backend/src/main/java/com/backend/domain/order/controller/OrderController.java
- backend/src/main/java/com/backend/domain/order/dto/OrderDetailsDto.java
- backend/src/main/java/com/backend/domain/order/dto/OrderDto.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderCreateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderDetailsCreateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/request/OrderStatusUpdateRequest.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderCreateResponse.java
- backend/src/main/java/com/backend/domain/order/dto/response/OrderDetailsCreateResponse.java
- backend/src/main/java/com/backend/domain/order/entity/OrderDetails.java
- backend/src/main/java/com/backend/domain/order/entity/OrderStatus.java
- backend/src/main/java/com/backend/domain/order/entity/Orders.java
- backend/src/main/java/com/backend/domain/order/repository/OrderRepository.java
- backend/src/main/java/com/backend/domain/order/service/OrderService.java
- backend/src/main/java/com/backend/global/response/ErrorCode.java
#43 
주문 관련 API 기능을 구현하는 과정입니다.
주문 생성 시 검증 로직 및 예외 처리 추가
사용자 주문 목록 조회 기능 기본 뼈대 구현
주문 상태 업데이트 기능 초안 작성
주문 생성 API 예외처리 (구현 완료)
유저 확인, 존재하지 않는 상품 , 상품 수량 0개 이하 변경, 금액 불일치 검증 로직 추가 예정
주문 상태 업데이트 (구현 완료)
주문 상태(CREATED -> PAID -> COMPLETED) 변경 기능 작성
잘못된 상태 전환 시 예외 처리 추가 예정
---------------------------
일단 예외처리까지 완료 했습니다. 
임의로 데이터베이스에 넣어놓고 테스트 해본 결과
예외 처리가 됩니다...
일단은 이메일로 해놓기는 했지만 이메일,총액, items를 제대로 넣는다면 정상적으로 db에 저장됩니다.
> feat: 주문 생성,상태 변경 기능 추가

- backend/src/main/java/com/backend/global/rq/Rq.java
쿠키, 헤더 관련 처리를 한곳에서 해줄 Rq클래스입니다. 
- 쿠키 헤더 정보를 읽어서 필요한 User 객체를 반환합니다.
- 쿠키 헤더 중에서 원하는 속성을 찾습니다.
- 쿠키 헤더에 원하는 값을 저장합니다.
선생님 코드 거의 복붙이라 크게 달라진 것이 없습니다.
누락되거나 실수한 부분 있으면 알려주세요.
> feature(rq) : 쿠키, 헤더 처리를 동시에 해줄 전역 클래스

- backend/src/main/java/com/backend/domain/cart/controller/CartController.java
- backend/src/main/java/com/backend/domain/cart/service/CartService.java
Closed #44
장바구니 메뉴 수량 변경 기능 구현
장바구니 수량을 입력 받아 최종 수량을 변경합니다.
즉, 수량 추가 & 삭제 둘다 가능합니다.
- 메뉴 수량 변경 Contorller 구현
- 메뉴 수량 변경 Service 구현
**⬇️ 수량을 0개 이하로 지정할 수 없습니다.**  <br>
**⬇️ 없는 메뉴를 추가할 수 없습니다.** <br>
> feat: 장바구니 메뉴 수량 변경 기능 구현

- backend/src/main/java/com/backend/domain/cart/controller/CartController.java
- backend/src/main/java/com/backend/domain/cart/service/CartService.java
Closed #60 
장바구니 각 메뉴를 삭제합니다.
- 장바구니에 있는 메뉴인지 확인
- 존재하는 회원인지 확인
- 메뉴 Id로 조회 후 해당 메뉴 삭제
> feature: 장바구니 메뉴 삭제 기능 구현

- backend/src/main/java/com/backend/domain/user/user/entity/Users.java
삭제된 의존성 패키지 import로 인한 문제 해결햇습니다.
> fix(user) : 삭제한 의존성 import로 인한 문제 해결

- backend/src/main/java/com/backend/domain/order/entity/Orders.java
- backend/src/main/java/com/backend/domain/order/service/OrderService.java
> fix:orderService 오류 수정

- backend/src/main/java/com/backend/domain/cart/controller/CartController.java
- backend/src/main/java/com/backend/domain/cart/repository/CartRepository.java
- backend/src/main/java/com/backend/domain/cart/service/CartService.java
Closed #78 
- Contoller - 삭제 요청 및 성공 응답
- Service - 예외처리 및 삭제 동작 처리
- Repository - 데이터베이스 접근 및 삭제 처리
장바구니 전체 삭제 기능 구현
- 삭제 후 아무것도 없음을 확인
✚ 원래 해당 기능 구현의 커밋만 올라가도록 하여 머지 플로우를 따라야하는 번거로움이 있었습니다.
충돌은 나지 않을테니 이번에는 그냥 올려볼까 합니다.. !
> feature: 장바구니 전체 삭제 기능 구현

- backend/src/main/java/com/backend/domain/user/user/controller/UserController.java
- backend/src/main/java/com/backend/domain/user/user/entity/Users.java
- backend/src/main/java/com/backend/domain/user/user/service/UserService.java
- backend/src/main/java/com/backend/global/response/ErrorCode.java
사용자 정보를 DTO에 담아와서 출력하는 API입니다.
전화번호 뿐이긴 하지만 사용자 정보를 수정하는 API입니다.
그 외 예외 처리 방식을 수정하였습니다.
로그아웃 시 예외 처리를 추가하였습니다. 
유효성 검증 로직이 컨트롤러에서 진행되던 것을 GlobalExceptionHandler에게 맡겼습니다.
로그인 되어 있는 경우
```Json
{
"code": "200",
"message": "정상적으로 완료되었습니다.",
"data": {
"userId": 1,
"userEmail": "test@mail.com",
"phoneNumber": "010-1234-1234",
"createDate": "2025-09-25T11:31:07.346662",
"modifyDate": "2025-09-25T11:31:07.346662",
"level": 1,
"apiKey": "713ce84e-4eb7-4a7c-8841-f7f036ff05ad"
}
}
```
로그인 되어 있지 않은 경우
```Json
{
"code": "U007",
"message": "로그인되어 있지 않습니다. 로그인 해 주십시오.",
"data": null
}
```
ApiKey의 UUID가 틀린 경우
```json
{
"code": "U002",
"message": "존재하지 않는 회원입니다.",
"data": null
}
```
로그인이 되어 있는 경우, 올바른 입력
```json
{
"code": "200",
"message": "정상적으로 완료되었습니다.",
"data": {
"userId": 1,
"userEmail": …
```
> feature(user) : 사용자 정보 조회 구현, 사용자 정보 수정 구현, 예외 처리 방식 일원화

- backend/src/main/java/com/backend/domain/cart/controller/CartController.java
- backend/src/main/java/com/backend/domain/menu/controller/MenuController.java
- backend/src/main/java/com/backend/global/config/SpringDoc.java
api 설계 규칙에 맞는 네이밍으로 변경했습니다. (menus / carts)
> chore: api 설계에 맞춘 네이밍 변경

- backend/src/main/java/com/backend/domain/user/address/entity/Address.java
- backend/src/main/java/com/backend/domain/user/address/service/AddressService.java
- backend/src/main/java/com/backend/domain/user/user/controller/UserController.java
- backend/src/main/java/com/backend/domain/user/user/dto/UserDto.java
- backend/src/main/java/com/backend/domain/user/user/entity/Users.java
- backend/src/main/java/com/backend/domain/user/user/service/UserService.java
Closes #121 
DB 조회가 너무 잦은 거 같아서 해당 부분 수정했습니다. 
테스팅 도중에 발견한 문제 해결
로직상 DB 조회 횟수를 줄였습니다.
> Fix(user), refactor(address) : 사용자 로그아웃 버그 수정, 주소 디비 조회횟수 감소

- frontend/src/app/orders/page.tsx
#155 
daa46a4 : 주문을 취소 할 때 잘못된 api로 호출하고 있었네요...
수정했습니다
취소와 삭제가 정상적으로 됩니다!!!
취소 했을 때 주문 내역에도 CANCELED 로 잘 뜹니다!
> fix:[FE] 주문 취소,삭제 시 결제->주문 순으로 취소,삭제 되게 설정

- backend/src/main/java/com/backend/domain/order/service/AdminOrderService.java
- backend/src/main/java/com/backend/domain/order/service/OrderService.java
- backend/src/main/java/com/backend/domain/payment/service/PaymentService.java
- frontend/src/app/payment/page.tsx
1. 장바구니 50000원 이하면 3000원 추가
백 + 프론트 로직 추가
2. 관리자 주문 조회에서 결재 조회 안됨 
결제 조회에서 관리자는 전부 허용하게 수정
3. paymentId가 null일때 오류 발생해서 조회가 안되는 현상
response dto에서 null 값 허용해서 해결
4. 주문 목록 조회 시 null 값이면 오류 생기는 현상
빈 리스트 반환하도록 하여 해결
> feature:[FE] 주문 관련 수정

- frontend/src/app/cart/page.tsx
- frontend/src/components/auth/AuthGuard.tsx
Closed #174 
로그인 상태에 따라 페이지 접근 시 나타나는 플로우를 다르게 설정했습니다.
⭕️ 로그인 : 페이지 접근 가능
❌ 로그아웃 : 로그인 페이지로 리다이렉트
> refactor(FE): 로그인 상태에 따른 페이지 접근 제한

- frontend/src/app/cart/page.tsx
- frontend/src/components/auth/AuthGuard.tsx
Closed #177 
불필요한 파일 삭제
- 작성하지 않은 test 더미 파일 삭제 
베이스 브랜치를 이전에 작업하던 브랜치로 잡아서 이전 커밋 목록이 함께 포함되어 있습니다.
`63fc408` 이 부분만 확인하시면 됩니다.
> refactor: 백엔드 파일에서 불필요한 파일 삭제

- frontend/src/app/orders/admin/page.tsx
- frontend/src/app/orders/page.tsx
- frontend/src/app/payment/page.tsx
- frontend/src/components/order/order-item.tsx
- frontend/src/types/order.ts
주문 관련 컴포넌트 및 타입을 분리하여 구조를 개선했습니다.
중복되거나 한 파일에 몰려 있던 로직을 정리해 관리성을 높이고, Order 타입을 공통적으로 사용할 수 있게 order.ts 파일에 분리했습니다.
> refactor: order 관련 컴포넌트 분리 및 타입 분리

- frontend/src/app/menu/page.tsx
> fix: 메뉴카드 경로 수정
